import { NOTIFICATION_TYPES } from "../constants/notificationTypes.js";

export async function buildNotificationPayload(notificationType, payload) {
  switch (notificationType) {
    case NOTIFICATION_TYPES.DEPARTMENT_CATEGORY_BUDGET_SUBMITTED:
    case NOTIFICATION_TYPES.DEPARTMENT_CATEGORY_REVIEW_COMPLETED:
    case NOTIFICATION_TYPES.CATEGORY_BUDGET_PACKAGE_SUBMITTED:
    case NOTIFICATION_TYPES.CATEGORY_BUDGET_PACKAGE_RETURNED:
    case NOTIFICATION_TYPES.CATEGORY_BUDGET_PACKAGE_COMPLETED:
    case NOTIFICATION_TYPES.CFO_ANNUAL_PACKAGE_REVIEW_FINALIZED:
    case NOTIFICATION_TYPES.DEPARTMENT_BUDGET_APPROVAL_UPDATED:
    case NOTIFICATION_TYPES.CATEGORY_SUBMISSION_WINDOW_CLOSED:
    case NOTIFICATION_TYPES.CATEGORY_SUBMISSION_WINDOW_REOPENED:
      return payload;

    case NOTIFICATION_TYPES.TRANSFER_CREATED:
    case NOTIFICATION_TYPES.TRANSFER_APPROVED:
    case NOTIFICATION_TYPES.TRANSFER_REJECTED:
      return payload;

    case NOTIFICATION_TYPES.ITEM_REQUEST_CREATED:
    case NOTIFICATION_TYPES.ITEM_REQUEST_APPROVED:
    case NOTIFICATION_TYPES.ITEM_REQUEST_REJECTED:
      return payload;
    case NOTIFICATION_TYPES.ADJUSTMENT_REQUEST_SUBMITTED:
    case NOTIFICATION_TYPES.ADJUSTMENT_REQUEST_APPROVED:
    case NOTIFICATION_TYPES.ADJUSTMENT_REQUEST_REJECTED:
      return payload;
    case NOTIFICATION_TYPES.PO_LINK_SUBMITTED:
    case NOTIFICATION_TYPES.PO_LINK_APPROVED:
    case NOTIFICATION_TYPES.PO_LINK_REJECTED:
      return payload;
    default:
      return payload;
  }
}
