export const NOTIFICATION_TYPES = {
  TRANSFER_CREATED: "TRANSFER_CREATED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",

  BUDGET_SUBMITTED: "BUDGET_SUBMITTED",
  BUDGET_APPROVED: "BUDGET_APPROVED",
  BUDGET_RETURNED: "BUDGET_RETURNED",

  ITEM_REQUEST_CREATED: "ITEM_REQUEST_CREATED",
  ITEM_REQUEST_APPROVED: "ITEM_REQUEST_APPROVED",
  ITEM_REQUEST_REJECTED: "ITEM_REQUEST_REJECTED",

  FINANCIAL_YEAR_OPENED: "FINANCIAL_YEAR_OPENED",
  FINANCIAL_YEAR_PRE_CLOSING: "FINANCIAL_YEAR_PRE_CLOSING",
  FINANCIAL_YEAR_CLOSED: "FINANCIAL_YEAR_CLOSED",

  PO_LINK_SUBMITTED: "PO_LINK_SUBMITTED",
  PO_LINK_APPROVED: "PO_LINK_APPROVED",
  PO_LINK_REJECTED: "PO_LINK_REJECTED",
};
