export const NOTIFICATION_TYPES = {
  TRANSFER_CREATED: "TRANSFER_CREATED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",

  BUDGET_SUBMITTED: "BUDGET_SUBMITTED",
  DEPARTMENT_CATEGORY_BUDGET_SUBMITTED:
    "DEPARTMENT_CATEGORY_BUDGET_SUBMITTED",
  CATEGORY_REVIEW_COMPLETED: "CATEGORY_REVIEW_COMPLETED",
  DEPARTMENT_BUDGET_APPROVAL_UPDATED: "DEPARTMENT_BUDGET_APPROVAL_UPDATED",
  CATEGORY_SUBMISSION_WINDOW_CLOSED: "CATEGORY_SUBMISSION_WINDOW_CLOSED",
  CATEGORY_SUBMISSION_WINDOW_REOPENED: "CATEGORY_SUBMISSION_WINDOW_REOPENED",
  CATEGORY_BUDGET_PACKAGE_SUBMITTED: "CATEGORY_BUDGET_PACKAGE_SUBMITTED",
  BUDGET_APPROVED: "BUDGET_APPROVED",
  BUDGET_RETURNED: "BUDGET_RETURNED",

  ITEM_REQUEST_CREATED: "ITEM_REQUEST_CREATED",
  ITEM_REQUEST_APPROVED: "ITEM_REQUEST_APPROVED",
  ITEM_REQUEST_REJECTED: "ITEM_REQUEST_REJECTED",

  FINANCIAL_YEAR_OPENED: "FINANCIAL_YEAR_OPENED",
  FINANCIAL_YEAR_PRE_CLOSING: "FINANCIAL_YEAR_PRE_CLOSING",
  FINANCIAL_YEAR_CLOSED: "FINANCIAL_YEAR_CLOSED",

  PO_LINK_SUBMITTED: "PO_LINK_SUBMITTED",
  PO_LINK_APPROVED: "PO_LINK_APPROVED",
  PO_LINK_REJECTED: "PO_LINK_REJECTED",
};
